---
# handlers file for ansible-role-airbyte

- name: restart airbyte
  community.docker.docker_compose:
    project_src: '{{ airbyte_docker_path }}'
    pull: yes
    nocache: yes
    recreate: smart
